---
- hosts: buildbox
  remote_user: ubuntu
  become: yes
  tasks:
  - name: install ansible repository
    apt_repository: repo='ppa:ansible/ansible'
  - name: install ansible to latest version
    apt: pkg={{ item }} state=latest update_cache=yes
    with_items:
      - ansible
      - git
      - python-pip
  - name: install boto
    command: pip install boto
  - name: remove default ansible hosts file
    file: path=/etc/ansible/hosts state=absent
  - name: copy directory to buildbox
    copy: src={{ item }} dest=/etc/ansible mode=0755
    with_items:
      - 'buildbox/hosts'
      - 'buildbox/ansible.cfg'
  - name: copy ssh directory to buildbox
    copy: src='buildbox/.ssh' dest=/home/ubuntu mode=0755
  - name: add aws env to profile
    lineinfile: dest=/etc/bash.bashrc line="export AWS_ACCESS_KEY_ID= \nexport AWS_SECRET_ACCESS_KEY="
  - name: config ssh config file
    lineinfile: dest=/etc/ssh/ssh_config line='    StrictHostKeyChecking no'
